name: Deploy to Production VM

on:
  push:
    branches: ['main'] # Se déclenche lors d'un push sur main
  workflow_dispatch: # Permet également un déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to VM using SSH
        uses: appleboy/scp-action@master
        with:
          host: 79.137.11.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/' # Le répertoire de sortie de build Vite
          target: '/home/ubuntu/brainforest' # Répertoire cible sur la VM

      - name: Configure application on VM
        uses: appleboy/ssh-action@master
        with:
          host: 79.137.11.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Installation de Nginx si nécessaire
            if ! command -v nginx &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y nginx
            fi

            # Déploiement des fichiers vers le répertoire web
            sudo mkdir -p /var/www/brainforest
            sudo cp -r /home/ubuntu/brainforest/dist/* /var/www/brainforest/
            sudo chown -R www-data:www-data /var/www/brainforest

            # Configuration de Nginx
            cat << 'EOF' | sudo tee /etc/nginx/sites-available/brainforest
            server {
                listen 80;
                server_name _;

                root /var/www/brainforest;
                index index.html;

                location / {
                    try_files $uri $uri/ /index.html;
                }
            }
            EOF

            # Activer le site et redémarrer Nginx
            sudo ln -sf /etc/nginx/sites-available/brainforest /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo systemctl restart nginx

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: 79.137.11.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Vérifier que Nginx est en cours d'exécution
            if systemctl is-active --quiet nginx; then
              echo "✅ Nginx is running"
            else
              echo "❌ Nginx is not running"
              exit 1
            fi

            # Vérifier que le site est accessible
            if curl -s --head --request GET http://localhost | grep "200 OK" > /dev/null; then
              echo "✅ Site is accessible"
            else
              echo "❌ Site is not accessible"
              exit 1
            fi

            echo "🚀 Déploiement terminé avec succès!"
