name: Deploy to Production VM

on:
  push:
    branches: ['main'] # Se déclenche lors d'un push sur main
  workflow_dispatch: # Permet également un déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to VM using SSH
        uses: appleboy/scp-action@master
        with:
          host: 79.137.11.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/' # Le répertoire de sortie de build Vite
          target: '/home/ubuntu/brainforest' # Répertoire cible sur la VM

      - name: Configure application on VM
        uses: appleboy/ssh-action@master
        with:
          host: 79.137.11.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Installation de Nginx si nécessaire
            if ! command -v nginx &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y nginx
            fi

            # Installation de Certbot pour les certificats SSL
            if ! command -v certbot &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y certbot python3-certbot-nginx
            else
            # S'assurer que le plugin Nginx est installé même si Certbot existe déjà
            sudo apt-get install -y python3-certbot-nginx
            fi

            # Déploiement des fichiers vers le répertoire web
            sudo mkdir -p /var/www/brainforest
            sudo cp -r /home/ubuntu/brainforest/dist/* /var/www/brainforest/
            sudo chown -R www-data:www-data /var/www/brainforest

            cat << 'EOF' | sudo tee /etc/nginx/sites-available/brainforest
            server {
                listen 80;
                listen 443 ssl;
                server_name brain-forest.works www.brain-forest.works;

                root /var/www/brainforest;
                index index.html;

                # Configuration SSL (sera mise à jour par certbot)
                ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
                ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

                # Paramètres SSL recommandés
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers on;
                ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
                ssl_session_cache shared:SSL:10m;

                location / {
                    try_files $uri $uri/ /index.html;
                }
            }
            EOF

            # Générer un certificat SSL auto-signé (en attendant Let's Encrypt)
            sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout /etc/ssl/private/nginx-selfsigned.key \
            -out /etc/ssl/certs/nginx-selfsigned.crt \
            -subj "/CN=localhost"

            # Activer le site et redémarrer Nginx
            sudo ln -sf /etc/nginx/sites-available/brainforest /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo systemctl restart nginx

            # Tenter d'obtenir automatiquement un certificat Let's Encrypt
            sudo certbot --nginx --non-interactive --agree-tos \
            --email basile.trebus-hamann@epitech.eu \
            -d brain-forest.works -d www.brain-forest.works || \
            echo "⚠️ Let's Encrypt n'a pas pu être configuré automatiquement."

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: 79.137.11.184
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if systemctl is-active --quiet nginx; then
              echo "✅ Nginx is running"
            else
              echo "❌ Nginx is not running"
              exit 1
            fi

            # Display headers for diagnostics
            echo "Checking HTTP headers:"
            curl -v --head --request GET http://localhost 2>&1

            # Improved HTTP verification - capture status code
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
            if [[ "$HTTP_STATUS" =~ ^(200|301|302|307|308)$ ]]; then
              echo "✅ HTTP site is accessible with code: $HTTP_STATUS"
            else
              echo "❌ HTTP site is not accessible. Received code: $HTTP_STATUS"
              exit 1
            fi

            if curl -sk --head --request GET https://localhost | grep "200 OK" > /dev/null; then
              echo "✅ Site HTTPS is accessible"
            else
              echo "❌ Site HTTPS is not accessible"
              exit 1
            fi

            echo "🚀 Deployment successful!"
