name: Code Quality Check

on:
  workflow_run:
    workflows: ['Node.js Build']
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            build
          key: ${{ runner.os }}-build-${{ github.event.workflow_run.head_sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: npm ci
      - run: npm run lint
